name: convert_to_wui
version: 0.0.2
homepage: https://github.com/davidmarne/convert_to_wui
author: David Marne <davemarne@gmail.com>
description: A tool for converting html files to wui_builder functions

dependencies:
  html: ^0.14.0+4
  dart_style: ^1.3.8

environment:
  sdk: ">=2.0.0 <3.0.0"
